config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'cart/index'
  resources :categories
  get 'contact-me', to: 'messages#new', as: 'new_message'
  post 'contact-me', to: 'messages#create', as: 'create_message'
  
  resources :types
  resources :products
  
  root 'static_pages#home'
  
  get '/contact', to: 'static_pages#contact'

  get '/about', to: 'static_pages#about'
  
  get 'category/:title', to: 'static_pages#category'
  
  get '/login', to: 'user#login'
  get '/logout', to: 'user#logout'
  
  
  
  get '/cart', to: 'cart#index'
  get '/cart/:id', to: 'cart#add'
  get '/cart/remove/:id', to: 'cart#remove'
  
  root :to => 'site#home'
  
  

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/message.rb
class Message 
    include ActiveModel::Model
    attr_accessor :name, :email, :message
    validates :name, :email, :message, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :authenticate_user!
  def index
    # pass the information to the view page of cart 
    if session[:cart] then
      @cart = session[:cart]
    else
      @cart = {}
    end  
    
  end
  
  
  def add 
    # get the id of the product we want to add
    
    id = params[:id]
    
    # if the session is already there use that if not make a new session
    
    if session[:cart]
      cart = session[:cart]
    else
      session[:cart] = {}
      cart = session[:cart]
    end  
    
    
    # if the product already is in the cart increase the quantity by 1
    
    if cart[id] then
      cart[id] = cart[id] + 1
    else 
      cart[id] = 1 
    end
    
    redirect_to :action => :index
    
  end
  
  
  def remove
    
    id = params[:id]
    cart = session[:cart]
     if cart[id] == 1 then
       cart.delete id
     else
     cart[id] = cart[id] - 1
    end
    redirect_to :action => :index
    
  end
 
end



  
  
  def remove
    
    id = params[:id]
    cart = session[:cart]
     if cart[id] == 1 then
       cart.delete id
     else
     cart[id] = cart[id] - 1
    end
    redirect_to :action => :index
    
  end
 
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :description, :image)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    def new
        @message = Message.new
    end
    
    def create
        @message = Message.new(message_params)
    
        if @message.valid?
            MessageMailer.contact_me(@message).deliver_now
            redirect_to new_message_url, notice: "Message received, thanks"
        else
          render :new
        end
    end
        

    private
    def message_params
        params.require(:message).permit(:name, :email, :message)
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :cost, :type, :image)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @categories = Category.all
  end

  def contact

  end

  def about
  end
  
  def category
    
    catName = params[:title]
    @products = Product.where("category like ?", catName)
    
    
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
    
    def login
        session[:login] = 1
        flash[:notice] = "You Logged In... Well Done!"
        redirect_to :controller => :items
    end
    
    
    def logout
        # session[:cart] = nil
        session[:login] = nil
        flash[:notice] = "Ok then see you next time!"
        redirect_to :controller => :items
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/cart/index.html.erb
<p id="notice"><%= notice %></p>


<table id="customers">
    <% total = 0 %>
    <% @cart.each do |id, quantity | %>
    
    <% item = Item.find_by_id(id) %>
        <tr>
        <td>
            <div class="image">
                <%= link_to (image_tag item.image_url, :style =>"height:40px"), item %>
        
            </div>
        </td>
        
        <td><%= link_to item.title, item %></td>
        <td><a href="/cart/remove/<%= item.id %>">Remove From Cart</a></td>
        <td><%= number_to_currency(item.price, :unit => "€") %> </td>
        <td><%= quantity %></td>
        <td><%= number_to_currency(quantity * item.price, :unit => "€") %></td>
    </tr>
    <tr> <% total += quantity * item.price %> 
        <td>
            Grand Total: <%= number_to_currency(total, :unit => "€") %>
            
        </td>
        
    </tr>
    
    <% end %>
    
</table>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :category_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :category_description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :category_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= category.description %></td>
        <td><%= category.image %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @category.image %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/_categories.html.erb
<h1>Main Categories</h1>


    
    <% @categories.each do |category| %>
        <div class="producthols">
    
    <h1><%= category.title %></h1>
    <%= link_to (image_tag category.image, :class => "productholsIm" ), category %>
    <p><%= category.description %></p>
    <p><a href="/category/<%= category.title %>"><%= category.title %></a></p>
    
        </div>
    <% end %>
    
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClothesRUs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <h1>ClothesRUs</h1>
      
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Products", products_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        
        <% if user_signed_in? %>
              <li><a href="#">Hi <%= current_user.email %></a></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
            <% else %>
              <li><%= link_to 'Register', new_user_registration_path %></li>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
            <% end %>
      </ul>
      
    </div>
    
     
    <div id='container'>
      <div id='content'>
        <p class='notice'><%= flash[:notice] %></p>
      <%= yield %>
      </div>
      <div id='first-column'>
        <div class="loginbox">
            <h2 class="BoxHeader">Search Catalog</h2>
            

        </div>
        
        <div class="searchbox">
          <h2 class="BoxHeade">Search Catalogue</h2>
        </div>
      </div>
 
    
    
    <div class="footer">
      <%= link_to 'New Category', new_category_path, :class =>"button", :role=>"button"  %>
      <%= link_to 'New Product', new_product_path, :class =>"button", :role=>"button"  %>
    </div>
  </body>
</html>

app/views/messages/new.html.erb
<%= form_for @message, url: create_message_url do |f| %>
  <%= notice %>
  <%= @message.errors.full_messages.join(', ') %>

  <%= f.text_field :name, placeholder: 'name' %>
  <%= f.email_field :email, placeholder: 'email' %>
  <%= f.text_area :message, placeholder: 'message' %>
  <%= f.submit 'Send' %>
<% end %>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="field">
    <%= form.label :cost %>
    <%= form.text_field :cost, id: :product_cost %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type, id: :product_type %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :product_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div id="itemsContainer">
  <h1>Products</h1>
  
      <% @products.each do |product| %>
    
             <div class="producthols">
        <h1><%= product.title %></h1>
     <%= link_to (product_tag product.image_url, :class => "productholsIm"), item %>
        <%= product.image_url %>
       
       <p><%= product.description %></p>
       <p>Price <%= number_to_currency(product.price, :unit =>"€") %>
       <br>
       Type: <%= product.type %>
       </p>
       
       
       <P>
        
        <% if user_signed_in? %>
        <%= link_to 'Show', product, :class =>"button", :role=>"button" %>
        <% end %>
        
        <a href="/cart/<%= product.id %>" class="button">Add To Cart</a>
        
         <% if session[:login] == 1 %>
        
        <%= link_to 'Edit', edit_product_path(product), :class =>"button", :role=>"button"  %>
        <%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure?' }, :class =>"button", :role=>"button"  %>
     
        <% end %>
     
     
     
     
     
     </P>
             </div>
    <% end %>
    
 </div>
<br>
<%= link_to 'New Item', new_item_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @product.cost %>
</p>

<p>
  <strong>Type:</strong>
  <%= @product.type %>
</p>

<p>
  <strong>Image:</strong>
  <%= @product.image %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/static_pages/Category.html.erb
<h1>Category products</h1>

<% if @products.length == 0 %>
<h2>Need some text here</h2>
<% end %>


 <% @products.each do |product| %>
    
             <div class="producthols">
        <h1><%= product.title %></h1>
     <%= link_to (image_tag product.image_url, :class => "productholsIm"), product %>
        <%= product.image_url %>
       
       <p><%= product.description %></p>
       <p>Price <%= number_to_currency(product.price, :unit =>"€") %>
       <br>
       Category: <%= product.category %>
       <br>
      
       
       
       <P>
        
        <% if user_signed_in? %>
        <%= link_to 'Show', product, :class =>"button", :role=>"button" %>
        <% end %>
        
        <a href="/cart/<%= product.id %>" class="button">Add To Cart</a>
        
         <% if session[:login] == 1 %>
        
        <%= link_to 'Edit', edit_product_path(product), :class =>"button", :role=>"button"  %>
        <%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure?' }, :class =>"button", :role=>"button"  %>
     
        <% end %>
     
     
     
     
     
     </P>
             </div>
    <% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>

<h1>About ClothesRUs!</h1>
<p>We are a fictional company that exists purely to give a sample of the Ruby-On-Rails website building technique.</p>
<p>We offer a similuation of an online clothing store. If you wish to actually buy a product from this site, we advice not to and instead look elsewhere</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<h1>Home</h1>

<p>
    hello
</p>

<h4>Categories</h4>
<br>

<%=render 'layouts/categories'%>

<% @categories.each do |category| %>
<div class="itemhols">

<p><%= category.description %></p>
</div>

<% end %>

app/views/types/_form.html.erb
<%= form_with(model: type, local: true) do |form| %>
  <% if type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :type_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :type_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @types.each do |type| %>
      <tr>
        <td><%= type.name %></td>
        <td><%= type.description %></td>
        <td><%= link_to 'Show', type %></td>
        <td><%= link_to 'Edit', edit_type_path(type) %></td>
        <td><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type', new_type_path %>

app/views/types/new.html.erb
<h1>New Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @type.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @type.description %>
</p>

<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>